### ISSUE TITLE
Having a Random background crashes

### ISSUE THREAD

**Issue by LapseType** [GabeHasWon/NewBeginnings#2]
Greetings, so my friend discovered that setting your background to Random from your mod crashes tModLoader...
Not used to making bug reports, so apologies if you may find this overwhelming...

Here's the log file I received from tModLoader.
[client.log](https://github.com/GabeHasWon/NewBeginnings/files/10333833/client.log)

If it helps, here's the list of mods I also enabled (that we're also planning to play with):
- AlchemistNPC Lite by VVV101, b2mauler, somebody0214, RebooT, drh
- AutoReforge by Sad Onion
- Auto Team Join by Dzejk
- Better Zoom by NotLe0n
- Boss Checklist by SheepishShepherd, jopojelly
- Boss Cursor by kgoyo
- Boss Fight Lives Per Player by AngelSpirit
- Census - Town NPC Checklist by jopojelly
- Compare Item Stats by direwolf420
- Magic Storage by The Magic Storage Team
- Movement Speed Fixed by OblivionAXiS
- New Beginnings by Team Spirit
- OmniSwing by gardenapple, Pop000100
- Orchid Mod by Verveine, S-Pladison, Multibanana
- Ore Excavator by CrazyContraption
- Persistent Boss Summon Items by Sausytime
- Recipe Browser by jopojelly
- Reduced Grinding by Dragon3025
- Thorium Mod by DivermanSam & the Goons
- Which Mod Is This From? (WMITF) by gardenapple, TGBGames91, Pop000100

![image](https://user-images.githubusercontent.com/58359861/210286309-7e8d577c-96a1-48b4-adc2-ce5db6d64ac8.png)

**Comment by GabeHasWon** [comment]
Thanks for the report! Had some changes in the backend and I didn't remember to update the Random origin properly. It's fixed in the upcoming update!
