### ISSUE TITLE
Extraneous ModSaveData File Being Created

### ISSUE THREAD

**Issue by steviegt6** [GabeHasWon/NewBeginnings#3]
An extra file (with the name `nb_unlocks.txt.txt`) is being created when saving unlocks.

https://github.com/GabeHasWon/NewBeginnings/blob/master/Common/UnlockabilitySystem/UnlockabilityIO.cs#L45-L46

1. The issue lies in appending `.txt` to the `filePath` variable despite it already having an extension.
2. This is wholly unnecessary, the file will be created regardless (hence why this was not caught earlier).

**Comment by GabeHasWon** [comment]
Fixed! Didn't notice that StreamWriter's ctor made a file as well.
